# Convert given array as sparse connected fcn

![](img/example1.png)

![](img/example2.png)

## Connection also represents its acitvation function
- 0 : not connectied
- 1 : linear 
- 2 : ReLU
- 3 : Sigmoid

**not equivalent with the image above, and also can be changed**

# References
- [Concatenate layer output with additional input data](https://discuss.pytorch.org/t/concatenate-layer-output-with-additional-input-data/20462)

In [2]:
import numpy as np
import torch
import torch.nn as nn

In [3]:
class MatrixForWANN() : 
    def __init__(self, mat, in_dim, out_dim) :       
        self.mat = mat
        self.in_dim = in_dim
        self.out_dim = out_dim

In [11]:
mat = np.array([[0,2,0,0,2,0,0,0,0,0],
                [2,0,2,0,0,0,0,0,0,0],
                [0,2,0,2,0,0,0,0,0,0],
                [0,0,0,0,0,1,1,0,0,0],
                [0,0,0,0,0,0,1,1,0,0],
                [0,0,0,0,0,0,0,0,0,3],
                [0,0,0,0,0,0,0,0,3,0]])
in_dim = 5
out_dim = 2
# hidden_dim calculated from in_dim and out_dim must be same
num_hidden_nodes = ((mat.shape[1] - in_dim) if 
              (mat.shape[1] - in_dim)==(mat.shape[0] - out_dim) 
              else -1)

In [12]:
mat_wann = MatrixForWANN(mat, in_dim, out_dim)

In [13]:
# first position represents row : FROM
mat[0]

array([0, 2, 0, 0, 2, 0, 0, 0, 0, 0])

In [14]:
# second position represents column : TO
mat[:, 0]

array([0, 2, 0, 0, 0, 0, 0])

In [15]:
# get destinations of input layer
mat[:num_hidden_nodes, :in_dim]

array([[0, 2, 0, 0, 2],
       [2, 0, 2, 0, 0],
       [0, 2, 0, 2, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
# get hidden nodes which is connected from input layer
# 1 : connected, 0 : not connected
# positional index : node index for given hidden node
hidden_nodes_connected_from_input = []
for i in range(num_hidden_nodes) : 
    hidden_nodes_connected_from_input.append(1 if mat[i, :in_dim].sum() != 0 else 0)
hidden_nodes_connected_from_input

[1, 1, 1, 0, 0]

In [ ]:
class WANNFCN(nn.Module) : 
    def __init__(self, mat_wann) : 
        super(WANNFCN, self).__init__()
        self.mat = mat_wann.mat
        self.in_dim = mat_wann.in_dim
        self.out_dim = mat_wann.out_dim
        self.num_hidden_nodes = ((self.mat.shape[0] - self.in_dim) if 
              (self.mat.shape[0] - self.in_dim)==(self.mat.shape[1] - self.out_dim) 
              else -1)
        assert self.hidden_dim == -1 # hidden_dim calculated from in_dim and out_dim must be same
        
    def forward(self, x) : # forward determines connections
        # 1. get indices of first nodes connected to first hidden layer
        # create hidden nodes which have connection from input layer only
        
        
        # 1. create hidden nodes and feed data
        '''
        fc_in={}
        for i in range(0,self.in_dim):
            fc_in['in(%d)'%i] = 

        In [7]: d["string5"]
        Out[7]: 'Hello'

        In [8]: d
        Out[8]: 
        {'string1': 'Hello',
         'string2': 'Hello',
         'string3': 'Hello',
         'string4': 'Hello',
         'string5': 'Hello',
         'string6': 'Hello',
         'string7': 'Hello',
         'string8': 'Hello',
         'string9': 'Hello'}
        '''
        return