In [4]:
from graphtorch import *
import numpy as np
import torch 
import torch.nn as nn

__Example 1__

In [5]:
mat1 = np.array([[0,2,0,0,2,0,0,0,0,0],
                [2,0,2,0,0,0,0,0,0,0],
                [0,2,0,2,0,0,0,0,0,0],
                [0,0,0,0,0,1,1,0,0,0],
                [0,0,0,0,0,0,1,1,0,0],
                [0,0,0,0,0,0,0,0,0,3],
                [0,0,0,0,0,0,0,0,3,0]])  
in_dim = 5   
out_dim = 2  
mat_wann1 = MatrixForWANN(mat1, in_dim, out_dim)  

In [6]:
activations = [None, None, nn.ReLU(), nn.Sigmoid()]  
constant_weight = 1 
model = WANNFCN(mat_wann1, activations, constant_weight)

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]])      

numpy_input = torch.from_numpy(numpy_input).float()  
model(numpy_input)  

[3, 2]
connection from input :  [0 2 0 0 2 0 0 0 0 0]
idx_input_col 0, activation_type 0
idx_input_col 1, activation_type 2

**first input node
tensor([[ 2.],
        [ 7.],
        [12.]], grad_fn=<ReluBackward0>)
idx_input_col 2, activation_type 0
idx_input_col 3, activation_type 0
idx_input_col 4, activation_type 2
4 input node

**input_node torch.Size([3, 1])
tensor([[ 2.],
        [ 7.],
        [12.]], grad_fn=<ReluBackward0>)

**wrap_activation torch.Size([3, 1])
tensor([[ 5.],
        [10.],
        [15.]], grad_fn=<ReluBackward0>)

**sum torch.Size([3, 1])
tensor([[ 7.],
        [17.],
        [27.]], grad_fn=<AddBackward0>)
idx_input_col 5, activation_type 0
idx_input_col 6, activation_type 0
idx_input_col 7, activation_type 0
idx_input_col 8, activation_type 0
idx_input_col 9, activation_type 0
connection from input :  [2 0 2 0 0 0 0 0 0 0]
idx_input_col 0, activation_type 2

**first input node
tensor([[ 1.],
        [ 6.],
        [11.]], grad_fn=<ReluBackward0>)
idx_input_

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000]], grad_fn=<CatBackward>)

__Example 2__

In [12]:
mat2 = np.array([[2,0,0,0,0,0],
                [0,0,0,3,0,1]])
in_dim = 5
out_dim = 1
mat_wann2 = sb.MatrixForWANN(mat2, in_dim, out_dim)  

In [13]:
model = sb.WANNFCN(mat_wann2, sb.activations)  

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]])      

#numpy_input = np.array([[1,2,3,4,5]])  
numpy_input = torch.from_numpy(numpy_input).float()  
model(numpy_input)  

[1]
connection from input :  [2 0 0 0 0 0]
idx_input_col 0, activation_type 2

**first input node
tensor([[ 1.],
        [ 6.],
        [11.]], grad_fn=<ReluBackward0>)
idx_input_col 1, activation_type 0
idx_input_col 2, activation_type 0
idx_input_col 3, activation_type 0
idx_input_col 4, activation_type 0
idx_input_col 5, activation_type 0
connection from input :  [0 0 0 3 0 1]
idx_input_col 0, activation_type 0
idx_input_col 1, activation_type 0
idx_input_col 2, activation_type 0
idx_input_col 3, activation_type 3

**first input node
tensor([[0.9820],
        [0.9999],
        [1.0000]], grad_fn=<SigmoidBackward>)
idx_input_col 4, activation_type 0
idx_input_col 5, activation_type 1
5 input node

**input_node torch.Size([3, 1])
tensor([[0.9820],
        [0.9999],
        [1.0000]], grad_fn=<SigmoidBackward>)

**wrap_activation torch.Size([3, 1])
tensor([[ 1.],
        [ 6.],
        [11.]], grad_fn=<MmBackward>)

**sum torch.Size([3, 1])
tensor([[ 1.9820],
        [ 6.9999],
       

tensor([[ 1.9820],
        [ 6.9999],
        [12.0000]], grad_fn=<AddBackward0>)

__Example 3__

In [15]:
mat3 = np.array([[2,0,0,3,0],
                [0,0,0,0,1]])    
in_dim = 5  
out_dim = 2    
mat_wann3 = sb.MatrixForWANN(mat3, in_dim, out_dim)

In [17]:
model = sb.WANNFCN(mat_wann3, sb.activations)

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]])      

#numpy_input = np.array([[1,2,3,4,5]])  
numpy_input = torch.from_numpy(numpy_input).float()  
model(numpy_input)  

[]
output 0
tensor([[ 1.9820],
        [ 6.9999],
        [12.0000]], grad_fn=<AddBackward0>)
output 1
tensor([[ 5.],
        [10.],
        [15.]], grad_fn=<MmBackward>)
{'output_0': tensor([[ 1.9820],
        [ 6.9999],
        [12.0000]], grad_fn=<AddBackward0>), 'output_1': tensor([[ 5.],
        [10.],
        [15.]], grad_fn=<MmBackward>)}


tensor([[ 1.9820,  5.0000],
        [ 6.9999, 10.0000],
        [12.0000, 15.0000]], grad_fn=<CatBackward>)

__Example 4__

In [19]:
mat4 = np.array([[3,0,1,0,0],
                [0,3,0,0,0],
                [0,0,0,2,0],
                [0,0,0,0,2],
                [0,0,1,2,0],
                [0,0,1,0,0]])
in_dim = 3
out_dim = 4
mat_wann4 = sb.MatrixForWANN(mat4, in_dim, out_dim)

In [21]:
model = sb.WANNFCN(mat_wann4, sb.activations)

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]])      

#numpy_input = np.array([[1,2,3,4,5]])  
numpy_input = torch.from_numpy(numpy_input).float()  
model(numpy_input)  

[2]
connection from input :  [3 0 1 0 0]
idx_input_col 0, activation_type 3

**first input node
tensor([[0.7311],
        [0.9975],
        [1.0000]], grad_fn=<SigmoidBackward>)
idx_input_col 1, activation_type 0
idx_input_col 2, activation_type 1
2 input node

**input_node torch.Size([3, 1])
tensor([[0.7311],
        [0.9975],
        [1.0000]], grad_fn=<SigmoidBackward>)

**wrap_activation torch.Size([3, 1])
tensor([[ 3.],
        [ 8.],
        [13.]], grad_fn=<MmBackward>)

**sum torch.Size([3, 1])
tensor([[ 3.7311],
        [ 8.9975],
        [14.0000]], grad_fn=<AddBackward0>)
idx_input_col 3, activation_type 0
idx_input_col 4, activation_type 0
connection from input :  [0 3 0 0 0]
idx_input_col 0, activation_type 0
idx_input_col 1, activation_type 3

**first input node
tensor([[0.8808],
        [0.9991],
        [1.0000]], grad_fn=<SigmoidBackward>)
idx_input_col 2, activation_type 0
idx_input_col 3, activation_type 0
idx_input_col 4, activation_type 0
connection from input :  [

tensor([[ 3.7311,  0.8808,  6.7311,  3.0000],
        [ 8.9975,  0.9991, 16.9975,  8.0000],
        [14.0000,  1.0000, 27.0000, 13.0000]], grad_fn=<CatBackward>)

__Example 5__ 

In [23]:
mat5 = np.array([[0,2,0,0,2,0,0,0,0,0],
                [2,0,2,0,0,0,0,0,0,0],
                [0,2,0,2,0,0,0,0,0,0],
                [0,0,0,0,0,1,1,0,0,0],
                [0,0,0,2,0,0,1,1,0,0],
                [0,0,0,0,0,0,0,0,0,3],
                [0,0,0,0,0,0,0,0,3,0]])
in_dim = 5
out_dim = 2
mat_wann5 = sb.MatrixForWANN(mat5, in_dim, out_dim)

In [24]:
model = sb.WANNFCN(mat_wann5, sb.activations)

numpy_input = np.array([[1,2,3,4,5],  
                        [6,7,8,9,10],  
                        [11,12,13,14,15]])      

#numpy_input = np.array([[1,2,3,4,5]])  
numpy_input = torch.from_numpy(numpy_input).float()  
model(numpy_input)  

[3, 2]
connection from input :  [0 2 0 0 2 0 0 0 0 0]
idx_input_col 0, activation_type 0
idx_input_col 1, activation_type 2

**first input node
tensor([[ 2.],
        [ 7.],
        [12.]], grad_fn=<ReluBackward0>)
idx_input_col 2, activation_type 0
idx_input_col 3, activation_type 0
idx_input_col 4, activation_type 2
4 input node

**input_node torch.Size([3, 1])
tensor([[ 2.],
        [ 7.],
        [12.]], grad_fn=<ReluBackward0>)

**wrap_activation torch.Size([3, 1])
tensor([[ 5.],
        [10.],
        [15.]], grad_fn=<ReluBackward0>)

**sum torch.Size([3, 1])
tensor([[ 7.],
        [17.],
        [27.]], grad_fn=<AddBackward0>)
idx_input_col 5, activation_type 0
idx_input_col 6, activation_type 0
idx_input_col 7, activation_type 0
idx_input_col 8, activation_type 0
idx_input_col 9, activation_type 0
connection from input :  [2 0 2 0 0 0 0 0 0 0]
idx_input_col 0, activation_type 2

**first input node
tensor([[ 1.],
        [ 6.],
        [11.]], grad_fn=<ReluBackward0>)
idx_input_

tensor([[1.0000, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000]], grad_fn=<CatBackward>)